"""empty message

Revision ID: 45557ab35630
Revises: 
Create Date: 2022-04-26 17:10:04.114690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45557ab35630'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookingStatus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flight',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('departureDate', sa.DateTime(), nullable=True),
    sa.Column('departureAirportName', sa.String(length=100), nullable=True),
    sa.Column('departureAirpotCode', sa.String(length=100), nullable=True),
    sa.Column('departureCity', sa.String(length=100), nullable=True),
    sa.Column('departureLocate', sa.String(length=100), nullable=True),
    sa.Column('arrivalDate', sa.DateTime(), nullable=True),
    sa.Column('arrivalAirportName', sa.String(length=100), nullable=True),
    sa.Column('arrivalAirportCode', sa.String(length=100), nullable=True),
    sa.Column('arrivalCity', sa.String(length=100), nullable=True),
    sa.Column('arrivalLocate', sa.String(length=100), nullable=True),
    sa.Column('ticketprice', sa.Float(), nullable=True),
    sa.Column('flightNumber', sa.String(length=100), nullable=True),
    sa.Column('seatCapacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('costumer', sa.String(length=200), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('outboundFlight', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['outboundFlight'], ['flight.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_id'], ['bookingStatus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    op.drop_table('flight')
    op.drop_table('bookingStatus')
    # ### end Alembic commands ###
